# Server name and running port
server:
  name: SpringForge
  port: 8080

# Base URL
base:
  backend:
    url: http://localhost:8080/
  frontend:
    url: http://localhost:8080/

spring:
  # Devtools configurations
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  # H2 database configurations
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

# JWT configurations
jwt:
  accessTokenExpireMs: 12000000  # JWT Access Token Expiration Time (in milliseconds)
  emailTokenExpireMs: 120000  # Email Verification Token Expiration Time (in milliseconds)

# jasypt configurations
jasypt:
  encryptor:
    password: "ravindercodes"
