# Server name and running port
server:
  name: SpringForge
  port: 8080

# Base URL
base:
  backend:
    url: http://localhost:8080/
  frontend:
    url: http://localhost:8080/


spring:
  # Devtools configurations
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  # H2 database configurations
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ENC(z8hD0b+9epGXZIp0RZ0Fy8Cn1f8akJ6Q5sdQHlB0EuHwSKuqyEM8/p0kUBp38ieO)
    password:
    platform: h2
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  # Email configurations
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: aecc305723ab8c
    password: 1e3354b3ba716d
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# "From" email configuration
mail:
  from: springforge@test.com

# JWT configurations
jwt:
  accessTokenExpireMs: 12000000  # JWT Access Token Expiration Time (in milliseconds)
  emailTokenExpireMs: 120000  # Email Verification Token Expiration Time (in milliseconds)


# jasypt configurations
jasypt:
  encryptor:
    password: "ravindercodes"







